### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by J-Bruski** [J-Bruski/coding-interview-training#1]
- [ ] git checkout -b progress

- [ ] git remote add jwasham https://github.com/jwasham/coding-interview-university

- [ ] git fetch --all

- [ ] git add .

- [ ] git commit -m "Marked x"

- [ ] git rebase jwasham/master

- [ ] git push --force
